-- MySQL Script generated by MySQL Workbench
-- Fri Jul 20 15:55:37 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema theWall
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema theWall
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `theWall` DEFAULT CHARACTER SET utf8 ;
USE `theWall` ;

-- -----------------------------------------------------
-- Table `theWall`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `theWall`.`messages` (
  `idMessages` INT NOT NULL,
  `valueMessages` VARCHAR(240) NOT NULL,
  `dateMessages` DATETIME NOT NULL,
  `urlMessages` VARCHAR(240) NULL,
  `photoMessages` TINYINT NULL,
  PRIMARY KEY (`idMessages`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
